apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nexus.name" . }}
    helm.sh/chart: {{ include "nexus.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      name: {{ .name }}
    {{- end}}
  selector:
    app.kubernetes.io/name: {{ include "nexus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
