## Global Docker image registry
### Please, note that this will override the image registry for all the images, including dependencies, configured to use the global value
###
## global:
##   imageRegistry:

## openproject/community openproject image version
## ref: https://hub.docker.com/r/bitnami/postgresql/tags/
##
image:
  registry: docker.io
  repository: openproject/community
  tag: 7.4
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: Always

## ingress settings - Optional
ingress:
  enabled: true

## chart defaults to using an ingress for http, but change to LoadBalancer if using you cluster supports it
service:
  http:
    serviceType: ClusterIP
    port: 8080
    #nodePort: 30280
    # sometimes if is necesary to access through an external port i.e. http(s)://<dns-name>:<external-port>
    externalPort: 8080
    externalHost: openproject.demo-pic.techlead-top.ovh

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  openprojectSize: 5Gi

existingSecret: false

securityContext:
  enabled: true
  fsGroup: 1000
  runAsUser: 1000

postgresql:
  # Enable to deploy the PostgreSQL chart
  enabled: true
  postgresqlDatabase: openproject
  postgresqlUsername: openproject
  postgresqlPassword: openproject
  image:
    tag: 9.6
