{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openproject.fullname" . }}
  labels:
    app: {{ template "openproject.name" . }}
    chart: {{ template "openproject.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if .Values.openprojectSecrectKey }}
  openproject-password: {{ .Values.openprojectSecrectKey | b64enc | quote }}
  {{- else }}
  openproject-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end -}}
